### PR TITLE
Sessionless redirect ux mode added

### PR DESCRIPTION
**Pull request by himanshuchawla009**

### CODE REVIEW

**Review by chaitanyapotti — APPROVED** [review]
lgtm

**Comment by holybasilonly** [comment]
Hi @chaitanyapotti & @himanshuchawla009 - We are getting following error since couple of days. I believe, this PR would be the cause of issue.

"Please pass loginProvider in params while using sessionless_redirect mode"

fyi here is the code

_const web3auth = new Web3Auth(WebBrowser, {
        clientId,
        network: Constants.expoConfig.extra.ENVIRONMENT == AppEnvironment.PRODUCTION ? OPENLOGIN_NETWORK.MAINNET : OPENLOGIN_NETWORK.TESTNET, // or other networks
      });
      
      web3auth.login({
            redirectUrl: WEB_REDIRECT_URL,
            mfaLevel: "none",
            curve: "secp256k1"
          });_

**Comment by himanshuchawla009** [comment]
Hey, does your app uses openlogin default default login modal?

**Comment by chaitanyapotti** [comment]
@holybasilonly loginProvider is mandatory in react native environment.
Pls pass it in

**Comment by holybasilonly** [comment]
> @holybasilonly loginProvider is mandatory in react native environment. Pls pass it in
We didn't pass any login provider as we need all providers for our app. We are using https://github.com/Web3Auth/web3auth-react-native-sdk

Ok, we can pass that but is there a way, we can pass more than one login provider ?
@himanshuchawla009 @chaitanyapotti

**Pull request merged**
